### ISSUE TITLE
datatables header fixed, in horizontal scroll, yet not supported? 

### ISSUE THREAD

**Issue by ijunaid8989** [DataTables/FixedHeader#74] opened 2015-12-16 05:42 UTC
I have been searching around and all what i found that old versions dont support that. 

Is there any update on this?

**Comment by DataTables** [comment] 2015-12-16 09:46
[Seems to work for me](http://live.datatables.net/palajori/1/edit) although perhaps I have misunderstood your question. Please link to a test case showing the issue.

**Comment by ijunaidfarooq** [comment] 2015-12-16 09:52
what you are showing me is for Vertical scroll not for horizontal scrolling,   
![image](https://cloud.githubusercontent.com/assets/13561999/11837727/938c95a6-a404-11e5-9ebb-168c3da1bf07.png)

I hope you will understand it now.

**Comment by DataTables** [comment] 2015-12-16 10:00
Oh I see - you mean you have enabled `scrollX` in DataTables? If so, then yes, FixedHeader is not supported with `scrollX` or `scrollY`.

**Comment by ijunaidfarooq** [comment] 2015-12-16 10:01
Okay :)

**Comment by ninjaonsafari** [comment] 2016-10-25 15:10
why have you closed this issue? this should be implemented...

**Comment by ijunaid8088** [comment] 2016-10-25 16:00
@ninjaonsafari Yeah I thought so as well.. But no body did anything yet.. 

Opening the issue,, may be I will work on it by myself..

**Comment by DataTables** [comment] 2016-10-25 16:02
Yup - this is something that should and will be implemented once I get some time to work on it.

**Comment by tmendesilva** [comment] 2017-03-10 14:24
Any news about this issue? tnks

**Comment by DataTables** [comment] 2017-03-10 14:27
No sorry. FixedHeader support for `scrollX` / `scrollY` is not a feature I'm like to get time to implement in the near future.

**Comment by DataTables** [comment] 2018-06-06 15:55
Closing as a duplicate of #7.

**Closed by DataTables** 2018-06-06 15:55 UTC
