### ISSUE TITLE
Header width gets randomized

### ISSUE THREAD

**Issue by MarioLipinski** [DataTables/FixedHeader#60] opened 2015-08-18 13:24 UTC
The header columns get resized when fixed header is used.... please see the fiddle for demo.

https://jsfiddle.net/fj2a9e1x/

**Comment by runofthemill** [comment] 2015-08-18 22:01
+1

**Comment by DataTables** [comment] 2015-09-08 13:56
This is a duplicate of #57 which I've just committed a fix for. [Update of your example](https://jsfiddle.net/fj2a9e1x/4/) with the fix applied in the nightly version.

**Closed by DataTables** 2015-09-08 13:56 UTC
